In [1]:
from scipy.special import comb
from itertools import combinations
import numpy as np
import copy
import math

In [2]:
N = 5
M = 5

In [3]:
H1 = 1
while (comb(H1 + M - 1, M - 1) <= N):
    H1 = H1 + 1
H1 = H1 - 1

In [4]:
W1 = np.array(list(combinations(range(H1 + M - 1), M - 1)))
W1

array([[0, 1, 2, 3],
       [0, 1, 2, 4],
       [0, 1, 3, 4],
       [0, 2, 3, 4],
       [1, 2, 3, 4]])

In [5]:
W2 = np.tile(np.array(list(range(M - 1))), (int(comb(H1 + M - 1, M - 1)), 1))
W2

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [6]:
W = np.array(list(combinations(range(H1 + M - 1), M - 1))) - np.tile(np.array(list(range(M - 1))),
                                                                     (int(comb(H1 + M - 1, M - 1)), 1))
W

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 1, 1]])

In [7]:
np.hstack((W, H1 + np.zeros((W.shape[0], 1))))

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.hstack((np.zeros((W.shape[0], 1)), W))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 1., 1., 1., 1.]])

In [1]:
5%11

5

In [9]:
# H1 = 1
# while (comb(H1 + M - 1, M - 1) <= N):
#     H1 = H1 + 1
# H1 = H1 - 1
# W = np.array(list(combinations(range(H1 + M - 1), M - 1))) - np.tile(np.array(list(range(M - 1))),
#                                                                      (int(comb(H1 + M - 1, M - 1)), 1))
# W = (np.hstack((W, H1 + np.zeros((W.shape[0], 1)))) - np.hstack((np.zeros((W.shape[0], 1)), W))) / H1
# if H1 < M:
#     H2 = 0
#     while (comb(H1 + M - 1, M - 1) + comb(H2 + M - 1, M - 1) <= N):
#         H2 = H2 + 1
#     H2 = H2 - 1
#     if H2 > 0:
#         W2 = np.array(list(combinations(range(H2 + M - 1), M - 1))) - np.tile(np.array(list(range(M - 1))),
#                                                                               (int(comb(H2 + M - 1, M - 1)), 1))
#         W2 = (np.hstack((W2, H2 + np.zeros((W2.shape[0], 1)))) - np.hstack((np.zeros((W2.shape[0], 1)), W2))) / H2
#         W2 = W2 / 2 + 1 / (2 * M)
#         W = np.vstack((W, W2))  # 按列合并
# W[W < 1e-6] = 1e-6
# N = W.shape[0]

In [10]:
N = 50
M = 3
H1 = 1
while (comb(H1 + M - 1, M - 1) <= N):
    H1 = H1 + 1
H1 = H1 - 1
W = np.array(list(combinations(range(H1 + M - 1), M - 1))) - np.tile(np.array(list(range(M - 1))),
                                                                     (int(comb(H1 + M - 1, M - 1)), 1))
W = (np.hstack((W, H1 + np.zeros((W.shape[0], 1)))) - np.hstack((np.zeros((W.shape[0], 1)), W))) / H1
if H1 < M:
    H2 = 0
    while (comb(H1 + M - 1, M - 1) + comb(H2 + M - 1, M - 1) <= N):
        H2 = H2 + 1
    H2 = H2 - 1
    if H2 > 0:
        W2 = np.array(list(combinations(range(H2 + M - 1), M - 1))) - np.tile(np.array(list(range(M - 1))),
                                                                              (int(comb(H2 + M - 1, M - 1)), 1))
        W2 = (np.hstack((W2, H2 + np.zeros((W2.shape[0], 1)))) - np.hstack((np.zeros((W2.shape[0], 1)), W2))) / H2
        W2 = W2 / 2 + 1 / (2 * M)
        W = np.vstack((W, W2))  # 按列合并
W[W < 1e-6] = 1e-6
N = W.shape[0]
N

45

In [25]:
a = np.array([])
np.append(a,np.array([1,2,3]), 0)

array([1., 2., 3.])

In [5]:
W[2][:]

array([1.0e-06, 2.5e-01, 7.5e-01])

In [13]:
a = [[2, 10, 5], [6, 7, 8]]
b = np.array([[3,4,5], [1,2,3]])
a.pop()
a

[[2, 10, 5]]

In [12]:
extreme = np.zeros(3)
w = np.zeros((3,3)) + 1e-6 + np.eye(3)
w

array([[1.000001e+00, 1.000000e-06, 1.000000e-06],
       [1.000000e-06, 1.000001e+00, 1.000000e-06],
       [1.000000e-06, 1.000000e-06, 1.000001e+00]])

In [3]:
np.sum(np.array([true,true]))

NameError: name 'true' is not defined

In [14]:
class Node:
    def __init__(self, at, node1=None, node2=None):
        self.attribute = at
        self.pa = node1
        self.of = node2
    def addnode(self, node):
        self.pa = node
        
        

In [15]:
node_a = Node(2)
node_b = Node(3)
node_a.addnode(node_b)
node_b.addnode(node_a)

In [ ]:
node_a.pa.